website/docs/intro.md
website/docusaurus.config.js
website/package-lock.json
website/package.json
website/src/theme/SearchBar/index.js

-  Adds a new search bar to the website
- Fixes the edit page feature

Searchbar added to website

---

.github/workflows/plan-examples.yml
analytics/emr-eks-karpenter/addons.tf
analytics/emr-eks-karpenter/examples/spark/compute-nytaxi-pyspark-karpenter.sh
analytics/emr-eks-karpenter/examples/spark/graviton-memory-nytaxi-pyspark-karpenter.sh
analytics/emr-eks-karpenter/examples/spark/memory-nytaxi-pyspark-karpenter.sh
analytics/emr-eks-karpenter/examples/spark/spark-scripts/pod-templates/graviton-memory-driver-pod.yaml
analytics/emr-eks-karpenter/examples/spark/spark-scripts/pod-templates/graviton-memory-executor-pod.yaml
analytics/emr-eks-karpenter/main.tf
analytics/emr-eks-karpenter/provisioners/spark-graviton-memory-optimized-provisioner.yaml
website/docs/amazon-emr-on-eks/emr-eks-karpenter.md

- Added a support for running Spark workloads on Graviton instances
- Docs updated
- Added Github workflow to run TF plan for PR's

Karpenter Graviton Provisioner support for EMR on EKS

---

analytics/emr-eks-karpenter/README.md
analytics/emr-eks-karpenter/addons.tf
analytics/emr-eks-karpenter/helm-values/kubecost-values.yaml
analytics/emr-eks-karpenter/helm-values/prometheus-values.yaml
analytics/emr-eks-karpenter/locals.tf
analytics/emr-eks-karpenter/main.tf

- Kubecost addon for EMR on EKS Karpenter pattern
- This addon uses the existing Prometheus deployment
Closes #46 

KubeCost addon for EMR on EKS Karpenter

---

.github/workflows/daily-tag.yml
.github/workflows/dependabot-automerge.yml

- Dependabot automerge workflow
- Create a Daily tag if there are any changes

daily tag gh flow added

---

website/docs/job-schedulers-eks/argo-workflows-eks.md
website/docs/job-schedulers-eks/aws-managed-airflow.md

fix broken link after folder structure change

---

streaming/kafka/README.md

Fix link to Kafka docs.

---

ADOPTERS.md
website/docs/amazon-emr-on-eks/emr-eks-ack.md
website/docs/amazon-emr-on-eks/emr-eks-fsx-for-lustre.md
website/docs/amazon-emr-on-eks/emr-eks-karpenter.md
website/docs/amazon-emr-on-eks/emr-eks-yunikorn.md
website/docs/amazon-emr-on-eks/index.md

Minor restructuring EMR on EKS pages to make it simple to consume and enabling for marketing purposes

Better positioning EMR on EKS

---

schedulers/terraform/argo-workflow/README.md
schedulers/terraform/argo-workflow/addons.tf
schedulers/terraform/argo-workflow/argo-events/sensor-sqs-sparkjobs.yaml
schedulers/terraform/argo-workflow/main.tf
website/docs/job-schedulers-eks/argo-workflows-eks.md

[enhancement] Change argo workflow example to create spark app in a new ns

---

analytics/terraform/emr-eks-karpenter/addons.tf
website/docs/amazon-emr-on-eks/emr-eks-karpenter.md
website/docs/amazon-emr-on-eks/index.md

Improving docs , see https://github.com/awslabs/data-on-eks/issues/66
Polishing EMR on EKS guidance
Removing Kubecost bcoz this is still WIP

EMR on EKS Doc improvement

---

website/src/pages/index.js

This font is not rendering properly on all websites

Removing the Robot font

---

analytics/terraform/emr-eks-karpenter/outputs.tf

Added EMR cluster Name to output.tf so instructions work

---

analytics/terraform/emr-eks-karpenter/README.md
analytics/terraform/emr-eks-karpenter/addons.tf
analytics/terraform/emr-eks-karpenter/examples/karpenter-memory-provisioner/execute_emr_eks_job.sh
analytics/terraform/emr-eks-karpenter/examples/karpenter-yunikorn-gangscheduling/execute_emr_eks_job.sh
analytics/terraform/emr-eks-karpenter/locals.tf
analytics/terraform/emr-eks-karpenter/outputs.tf
analytics/terraform/emr-eks-karpenter/provisioners/spark-compute-optimized-provisioner.yaml
analytics/terraform/emr-eks-karpenter/variables.tf
analytics/terraform/spark-k8s-operator/addons.tf
analytics/terraform/spark-k8s-operator/helm-values/aws-for-fluentbit-values.yaml
analytics/terraform/spark-k8s-operator/helm-values/nginx-values.yaml
analytics/terraform/spark-k8s-operator/helm-values/spark-k8s-operator-values.yaml

- Spark UI added for Spark Operator
- EMR on EKS Karpenter updates

Spark Live UI added

---

ADOPTERS.md
analytics/terraform/emr-eks-karpenter/main.tf

Update Adopters and Add policy of SSM to karpenter role

---

workshop/utilities/pre-requisites-setup.sh

add workshop util

---

workshop/eks/addons.tf

fix for karpenter provisioner

---

README.md
schedulers/terraform/argo-workflow/README.md
schedulers/terraform/managed-airflow-mwaa/README.md
schedulers/terraform/self-managed-airflow/README.md

Corrects the documentation website URL in the README.md file.
Providing the most up-to-date info.

Correct URL in README.md

---

.github/PULL_REQUEST_TEMPLATE.md
analytics/terraform/emr-eks-ack/README.md
analytics/terraform/emr-eks-ack/addons.tf
analytics/terraform/emr-eks-ack/cleanup.sh
analytics/terraform/emr-eks-ack/data.tf
analytics/terraform/emr-eks-fargate/addons.tf
analytics/terraform/emr-eks-fargate/cleanup.sh
analytics/terraform/emr-eks-fargate/install.sh
analytics/terraform/emr-eks-fargate/vpc.tf
analytics/terraform/emr-eks-karpenter/README.md
analytics/terraform/emr-eks-karpenter/addons.tf
analytics/terraform/emr-eks-karpenter/cleanup.sh
analytics/terraform/emr-eks-karpenter/helm-values/aws-cloudwatch-metrics-values.yaml
analytics/terraform/emr-eks-karpenter/variables.tf
workshop/eks/main.tf
workshop/eks/versions.tf

- Added `preserve=true` for key managed add-ons to avoid destroy issues
- Updated Install and cleanup shell scripts with stuck terminating namespace
- pre-commit formatting

added preserve field to true to avoid destroy issues

---

website/docs/amazon-emr-on-eks/emr-eks-karpenter.md

simplifying deployment experience

---

analytics/terraform/emr-eks-karpenter/pre-requisites-setup.sh
analytics/terraform/emr-eks-karpenter/providers.tf

Apac workshop

---

analytics/terraform/emr-eks-karpenter/addons.tf
analytics/terraform/emr-eks-karpenter/helm-values/kubecost-values.yaml

update emr eks job scripts

---

analytics/terraform/emr-eks-karpenter/examples/nvme-ssd/karpenter-compute-provisioner/execute_emr_eks_job.sh
analytics/terraform/emr-eks-karpenter/examples/nvme-ssd/karpenter-graviton-memory-provisioner/execute_emr_eks_job.sh
analytics/terraform/emr-eks-karpenter/examples/nvme-ssd/karpenter-memory-provisioner/execute_emr_eks_job.sh
analytics/terraform/emr-eks-karpenter/examples/nvme-ssd/karpenter-yunikorn-gangscheduling/execute_emr_eks_job.sh
analytics/terraform/emr-eks-karpenter/pre-requisites-setup.sh

Apac workshop - fix spark submission issues

---

analytics/terraform/emr-eks-karpenter/karpenter-provisioners/spark-compute-optimized-provisioner.yaml
analytics/terraform/emr-eks-karpenter/karpenter-provisioners/spark-graviton-memory-optimized-provisioner.yaml
analytics/terraform/emr-eks-karpenter/karpenter-provisioners/spark-memory-optimized-provisioner.yaml

update karpenter provisioner

---

analytics/terraform/emr-eks-karpenter/addons.tf
analytics/terraform/emr-eks-karpenter/variables.tf

Update for the APAC workshop to fix the bug for the instructions
- [ X] E2E Test successfully complete before merge?

update cluster_autoscaler and default region

---

website/package-lock.json
website/package.json

- Security fixes with Docusaurus NPM packages. Thanks to Github security dependabots for identifying these and I am having fun with these npm dependencies 😆

Security critical fixes for docusaurus

---

website/docs/amazon-emr-on-eks/emr-eks-karpenter.md

updated website doc for delta lake example

---

analytics/terraform/emr-eks-karpenter/karpenter-provisioners/spark-graviton-memory-optimized-provisioner.yaml
analytics/terraform/emr-eks-karpenter/karpenter-provisioners/spark-memory-optimized-provisioner.yaml

fix user-data bootstrap shell script err

---

analytics/terraform/emr-eks-karpenter/addons.tf

disable some addons

---

analytics/terraform/emr-eks-karpenter/variables.tf

disable grafana by default

---

website/docs/ai-ml/ray.md

Workshop instruction to include observability

---

.github/workflows/pr-title.yml
.github/workflows/stale-issue-pr.yml
README.md

- Updated broken readme links 
- added two github worklflows for stale issues

Updated readme with correct links

---

.github/workflows/plan-examples.py
.pre-commit-config.yaml
analytics/terraform/datahub-on-eks/README.md
analytics/terraform/datahub-on-eks/data.tf
analytics/terraform/datahub-on-eks/datahub-addon/modules/prereq/main.tf
analytics/terraform/datahub-on-eks/datahub-addon/modules/prereq/outputs.tf
analytics/terraform/datahub-on-eks/datahub-addon/modules/prereq/variables.tf
analytics/terraform/datahub-on-eks/datahub-addon/modules/prereq/versions.tf
analytics/terraform/datahub-on-eks/datahub-addon/versions.tf
analytics/terraform/datahub-on-eks/outputs.tf
analytics/terraform/datahub-on-eks/providers.tf
analytics/terraform/datahub-on-eks/versions.tf

- Fix linting errors to pass CI checks
- Ensure CI checks are passing and green

chore: Fix linting errors to pass CI checks

---

website/docs/blueprints/job-schedulers/self-managed-airflow.md

- Update Karpenter provisioner codeblock for self-managed Airflow
- I missed this one in the prior PR

chore: Update Karpenter provisioner codeblock for self-managed Airflow

---

analytics/terraform/emr-eks-karpenter/emr-eks-karpenter/emr-eks.tf
analytics/terraform/emr-eks-karpenter/emr-eks.tf

[apac-workshop branch] remove s3 private acl for 

---

analytics/terraform/emr-eks-karpenter/helm-values/kube-prometheus-amp-enable.yaml
schedulers/terraform/managed-airflow-mwaa/README.md
website/docs/blueprints/amazon-emr-on-eks/emr-eks-karpenter.md

- Added a fix to Grafana values to ensure service account is disabled

feat: Grafana service account fix

---

schedulers/terraform/argo-workflow/addons.tf
schedulers/terraform/argo-workflow/helm-values/kube-prometheus-amp-enable.yaml
schedulers/terraform/argo-workflow/helm-values/kube-prometheus.yaml
streaming/kafka/addons.tf
streaming/kafka/helm-values/kube-prometheus-amp-enable.yaml
streaming/kafka/helm-values/kube-prometheus.yaml
streaming/nifi/README.md
streaming/nifi/addons.tf
streaming/nifi/helm-values/kube-prometheus-amp-enable.yaml
streaming/nifi/helm-values/kube-prometheus.yaml

Add output gp3 storageClass to kube-prometheus-stack
gp3 storageClass to be created when kube-promtheus-stack is installed.

chore: Add output gp3 storageClass to kube-prometheus-stack

---

streaming/kafka/helm-values/kube-prometheus-amp-enable.yaml
streaming/kafka/helm-values/kube-prometheus.yaml

Fix for Kafka missing metrics in Grafana

fix: Missing Kafka metrics in Grafana dashboard

---

streaming/kafka/main.tf

Modify min_size = 3 and desired_size = 5 for kafka nodegroup

refactor: Modify min_size and desire_size for kafka nodegroup

---

website/docs/blueprints/streaming-platforms/flink.md

Updated a the instructions to correct some typos.

docs: Updated typos

---

tfsec.yaml

- removed some duplicates and added two exclusions

fix: Updated tfsec and removed duplicates

---

ai-ml/jark-stack/terraform/cleanup.sh
ai-ml/jark-stack/terraform/install.sh
ai-ml/jark-stack/terraform/src/app/streamlit.yaml

Fixes timeouts occurring during `install.sh` as well as `cleanup.sh` in the jark-stack

fix: Timeout in install.sh and cleanup.sh in the jark-stack

---

.pre-commit-config.yaml
ai-ml/trainium-inferentia/addons.tf

- This issue adds a new Volcano Helm chart to Trainium on EKS blueprint
Closes #318 #304 
- [ x] Yes, I have tested the PR using my local account setup (Provide any test evidence report under Additional Notes)
Completed cleaned my repo and resynced with fork. there was a manifest part for volcano added which i deleted (as we are using helm charts in this case)

feat: Volcano Helm chart added to Trainium blueprint

---

ai-ml/jark-stack/terraform/addons.tf

Fixes an error folks are getting when they are deploying JARK stack.
```
2023-10-19T15:05:35Z [Warning] MountVolume.MountDevice failed for volume "pvc-9ca7e116-6cfa-41a5-a51f-bd117d702582" : rpc error: code = Internal desc = could not format "/dev/nvme2n1" and mount it at "/var/lib/kubelet/plugins/kubernetes.io/csi/ebs.csi.aws.com/10b15dc2a4d440aa6d5488001bdbd4ace86f07be7332c66144624859a542a027/globalmount": mount failed: exit status 32 Mounting command: mount Mounting arguments: -t xfs -o …
```

fix: Change fs type to work around EBS CSI driver issue

---

ai-ml/jark-stack/terraform/cleanup.sh

fix cleanup script for jark-stack blueprint
cleanup script doesn't work if pattern gets deployed to different region than `us-west-2`

fix cleanup script for jark-stack blueprint

---

website/docs/introduction/intro.md

Added links for "KubeFlow, MLFlow, Tensorflow, PyTorch"
🚀 AI/ML on Kubernetes (e.g., KubeFlow, MLFlow, Tensorflow, PyTorch etc.)
to match the other examples listed on that page.
Consistency, Community, Contribution ;-)

Provided links to Open Source project landing page for Services listed

---

website/docs/gen-ai/training/Llama2.md

Updates llama2/trainium doc to use correct TF_VAR_ variables (important) and align to the recent blog.

Correct typos and sync with blog post

---

schedulers/terraform/self-managed-airflow/addons.tf

docs: Typo in documentation

---

analytics/terraform/emr-eks-karpenter/addons.tf
analytics/terraform/emr-eks-karpenter/examples/nvme-ssd/karpenter-compute-provisioner/driver-pod-template.yaml
analytics/terraform/emr-eks-karpenter/examples/nvme-ssd/karpenter-compute-provisioner/executor-pod-template.yaml
analytics/terraform/emr-eks-karpenter/karpenter-provisioners/spark-compute-optimized-provisioner.yaml
analytics/terraform/emr-eks-karpenter/karpenter-provisioners/spark-graviton-memory-optimized-provisioner.yaml
analytics/terraform/emr-eks-karpenter/karpenter-provisioners/spark-memory-optimized-provisioner.yaml

Karpenter Fixes

---

ai-ml/nvidia-triton-server/README.md
ai-ml/nvidia-triton-server/helm-values/ingress-nginx-values.yaml
ai-ml/nvidia-triton-server/helm-values/kube-prometheus.yaml
ai-ml/nvidia-triton-server/install.sh
ai-ml/nvidia-triton-server/nvidia-triton-server.tf
ai-ml/nvidia-triton-server/outputs.tf
ai-ml/nvidia-triton-server/variables.tf
website/docs/gen-ai/inference/vLLM-NVIDIATritonServer-Llama2.md

- Adds helm-values files for `kube-prometheus` stack and `nginx-ingress-controller`.
- Adds code for s3 sync
- Adds output variables for s3 bucket
- Adds module dependency to remove error for prometheus operator
- Adds website documentation for the blueprint.
Adds enhancements to the original blueprint
Closes #518

feat: Triton server vllm blueprint enhancements

---

.github/workflows/plan-examples.yml
analytics/terraform/superset-on-eks/addons.tf
analytics/terraform/superset-on-eks/helm-values/superset-values.yaml
website/docs/blueprints/distributed-databases/clickhouse.md

- Security recommendation fix for github workflows to run plan-examples
- This is the SHA (`${{github.event.pull_request.head.sha}}`) of the latest commit on the head branch of the pull request. It's a unique identifier that always points to the same, specific commit.
- It's immutable and will not change, even if the PR is updated with new commits.

fix: Updated sec fix to Github workflows to pr commit sha

---

ai-ml/nvidia-triton-server/README.md
ai-ml/nvidia-triton-server/nvidia-triton-server.tf
ai-ml/nvidia-triton-server/versions.tf

- added fix for the model deployment with s3 sync

fix: Triton deployment path fix

---

website/docs/gen-ai/inference/vLLM-NVIDIATritonServer-Llama2.md

Fix minor typo: s/model_reposiotry/model_repository/

Fix minor typo in path

---

gen-ai/inference/vllm-nvidia-triton-server-gpu/model_repository/llama2/1/model.py
gen-ai/inference/vllm-nvidia-triton-server-gpu/model_repository/llama3/1/model.py
gen-ai/inference/vllm-nvidia-triton-server-gpu/model_repository/llama3/config.pbtxt

…ssue and formating in each model python script
- Added [Llama3 8B Instruct model](https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct) for triton-server pattern
- Fixed minor issue from each model python script and formating

feat: Add Llama3 model for triton-server pattern

---

ai-ml/nvidia-triton-server/nvidia-nim.tf
gen-ai/inference/nvidia-nim/nim-client/client.py
website/docs/gen-ai/inference/nvidia-nim-llama3.md

- Fixed nim-client script to avoid `OPENAI_API_KEY` missing, as nim-client is using openai client, but the api key is not necessary;
- Updated nim-llm helm chart dependency; added one more dependency on ingress-nginx adddon
- Updated nim pattern website page. Updated the Grafana dashboard access instructions to make it more clearer to follow; also fixed some formatting.  
Based on the feedback collected from users.

fix: NIM Pattern Enhancement 20240716

---

ai-ml/kubeflow/README.md

chore: Delete ai-ml/kubeflow directory

---

website/docs/gen-ai/inference/Llama2-inf2.md
website/docusaurus.config.js
website/package-lock.json
website/package.json
website/src/components/VideoGrid/VideoGrid.js
website/src/components/VideoGrid/VideoGrid.module.css
website/src/css/fonts.css
website/src/pages/index.js
website/src/pages/index.module.css

- Updated home page buttons
- Added additional Gen AI button to make it easier to refer to blueprints
- Video formatting is now changed and added left and right arrow buttons

feat: Website Updates

---

gen-ai/inference/vllm-rayserve-inf2/openai-webui-deployment.yaml
gen-ai/inference/vllm-rayserve-inf2/vllm-rayserve-deployment.yaml

- Adds OpenWebUI deployment for testing the inference endpoint.
- Updates serve script to add OpenAI model discovery endpoint.
Adds OpenWebUI deployment for testing the inference endpoint.
Updates serve script to add OpenAI model discovery endpoint.

feat: Add OpenWebUI for vllm-rayserve-inf2 blueprint

---

ai-ml/trainium-inferentia/addons.tf
ai-ml/trainium-inferentia/eks.tf
ai-ml/trainium-inferentia/helm-values/jupyterhub-values.yaml
analytics/terraform/emr-eks-karpenter/examples/ebs-hostpath/karpenter-compute-provisioner/driver-pod-template.yaml
analytics/terraform/emr-eks-karpenter/examples/nvme-ssd/karpenter-compute-provisioner/driver-pod-template.yaml
analytics/terraform/emr-eks-karpenter/examples/nvme-ssd/karpenter-graviton-memory-provisioner/driver-pod-template.yaml
analytics/terraform/emr-eks-karpenter/examples/nvme-ssd/karpenter-graviton-memory-provisioner/executor-pod-template.yaml
analytics/terraform/emr-eks-karpenter/examples/nvme-ssd/karpenter-memory-provisioner/driver-pod-template.yaml
analytics/terraform/emr-eks-karpenter/examples/nvme-ssd/karpenter-memory-provisioner/executor-pod-template.yaml
analytics/terraform/emr-eks-karpenter/examples/nvme-ssd/karpenter-yunikorn-gangscheduling/driver-pod-template.yaml
analytics/terraform/emr-eks-karpenter/examples/nvme-ssd/karpenter-yunikorn-gangscheduling/executor-pod-template.yaml
gen-ai/inference/vllm-llama3.1-405b-trn1/README.md
gen-ai/inference/vllm-llama3.1-405b-trn1/docker/Dockerfile
gen-ai/inference/vllm-llama3.1-405b-trn1/docker/run.sh
gen-ai/inference/vllm-llama3.1-405b-trn1/gradio-client.yaml
gen-ai/inference/vllm-llama3.1-405b-trn1/llama3-405b-vllm-lws-deployment.yaml
gen-ai/inference/vllm-rayserve-inf2/vllm-rayserve-deployment.yaml

- Updates to Llama3.1 405 b model inference scripts
-

feat: Updates to the llama3.1 405 model scripts

---

schedulers/terraform/aws-batch-eks/README.md
website/docs/blueprints/job-schedulers/aws-batch.md

Fixed a link to the blueprint directory on the AWS Batch documentation page.
Reported error

docs: Fix a link in AWS Batch instructions

---

website/src/theme/Footer/index.js

https://github.com/awslabs/data-on-eks/issues/593
Adds cloudflare insights.

style: Add cf insights

---

website/package-lock.json

- 🔒 Fix security vulnerabilities by updating dependencies (`path-to-regexp`, `express`, `serve-handler`)
🚀💉 Security Patch Time! Fixing `path-to-regexp` Before It Wreaks Havoc!

feat: Fixes to security vulnerabilities

---

website/docs/blueprints/ai-ml/jark.md

JARK Doc refactor for blueprint
This adjust the path to the install.sh file for  the blueprint refactor for JARK Stack

docs: Minor changes to JARK docs for the blueprint refactor

---

analytics/terraform/spark-k8s-operator/addons.tf

https://kubernetes.io/blog/2025/03/24/ingress-nginx-cve-2025-1974/

fix: Update ingress-nginx

---

README.md
website/docs/blueprints/job-schedulers/aws-batch.md
website/docusaurus.config.js
website/src/components/HomepageFeatures/index.js
website/src/pages/index.js

- Updates references to Ai on EKS repo
- Website modified to use only Data Icons
- Readme updated with more details
- Added moving section to Ai on EKS on the top bar
New page after this update

feat: Updates to AI on EKS repo

---

website/docs/blueprints/distributed-databases/aerospike.md

This PR adds the Aerospike Blueprint landing page to the DoEKS project
Adding the Aerospike blueprint to the doEKS project simplifies and accelerates the deployment of Aerospike Enterprise on EKS with best practices.

feat: Add Aerospike blueprint

---

analytics/terraform/spark-k8s-operator/examples/benchmark/spark-operator-benchmark-kit/emr-eks-grafana-dashboard.json

updates the EMR dashboard to allow multiple driver pods to be selected, and updates the panels to work with multiple results.
While running the workshop we realized there isn't a way to see multiple jobs in the dashboard simultaneously.
This needs to be tested and I'm not positive the queries are exactly what we want but i didn't go through all of them for validity.

feat: Add multi-select and update panels to spark workshop

---

analytics/terraform/spark-k8s-operator/examples/raydata-sparklogs-processing-job/execute-rayjob.sh
analytics/terraform/spark-k8s-operator/examples/raydata-sparklogs-processing-job/verify-iceberg-data.sh
website/docs/blueprints/data-analytics/ray-data-processing.md
website/src/components/TechMarquee/TechMarquee.js

Update website doc to link to the blueprint

docs: Update website doc to link to the blueprint

---

analytics/terraform/spark-k8s-operator/README.md
analytics/terraform/spark-k8s-operator/jupyterhub.tf

- Added a bedrock IAM policy to JupyterHub Notebooks

feat: Added bedrock IAM policy to JupyterHub Notebooks

---

website/src/components/WorkshopBanner/WorkshopBanner.js
website/src/components/WorkshopBanner/WorkshopBanner.module.css
website/src/pages/index.js

- Added links to the Website homepage with Spark on EKS workshop links

docs: Added Spark workshop links to Website homepage
