- analytics/emr-eks-karpenter/addons.tf
Fixed the hard-coded Karpenter region in the example.
In case people may not use the default region (eu-west-1), and the karpenter doesn't work well due to the setting.
N/A
> fix: Fixed the karpenter example hard-coded the provisioner region

- .github/workflows/plan-examples.yml
- Github workflow security updates to fix the following issues
1. The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
2. Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update …
> Github workflow security updates

- website/blog/2022-11-28-emr-eks-emr-studio.md
Fix the AWS CLI command to submit a job
> Fix the aws cli command

- schedulers/terraform/argo-workflow/README.md
- schedulers/terraform/argo-workflow/addons.tf
- schedulers/terraform/argo-workflow/argo-events/sensor-sqs-sparkjobs.yaml
- schedulers/terraform/argo-workflow/argo-events/sqs-accesspolicy.json
- schedulers/terraform/argo-workflow/helm-values/aws-for-fluentbit-values.yaml
- schedulers/terraform/argo-workflow/helm-values/prometheus-values.yaml
- schedulers/terraform/argo-workflow/main.tf
> [enhancement] update argo workflows based on blog comments

- analytics/terraform/emr-eks-karpenter/examples/karpenter-compute-provisioner/execute_emr_eks_job.sh
Modifying pyspark job submission by using input variables rather than hardcoding in the example job.
> modifying job submission by changing to input variables rather than hardcoding

- analytics/terraform/emr-eks-karpenter/examples/karpenter-compute-provisioner/execute_emr_eks_job.sh
There was a minor bug which was leading to json error. Fixing this bug should let the job submission run successfully
> minor bug in compute provisioner script

- ADOPTERS.md
> Removing link from Adopters page

- website/docs/ai-ml/ray.md
It fixes an error in the documentation for the ray pytorch example, specifically in the port-forwarding call.
It's an easy fix I noticed while implementing the example.
I didn't run any tests since it's a simple documentation fix.
> Fix documentation error in ray pytorch example

- analytics/terraform/spark-k8s-operator/addons.tf
- Removed the cluster name variable to fix the missing variable issue. This variable has been removed from the module for now.
> Removed the cluster name variable

- analytics/terraform/emr-eks-karpenter/outputs.tf
> add output for amp

- ai-ml/ray/terraform/examples/xgboost/main.tf
- ai-ml/ray/terraform/examples/xgboost/variables.tf
The Ray on EKS terraform module deploys to us-west-2 by default. The XGBoost example project declared us-east-1 as the region.
This commit moves the variable to variables.tf and defaults it to us-west-2.
Fixes #203 
It's broke yo
- [X ] Yes, I have tested the PR using my local account setup (Provide any test evidence report under Additional Notes)
Tested locally with `terraform plan`
> Fix region mismatch in XGBoost example

- ai-ml/ray/terraform/examples/pytorch/main.tf
- ai-ml/ray/terraform/examples/pytorch/variables.tf
The Ray on EKS module deploys to us-west-2, the example application attempts to target us-east-1.
This commit moves the region to variables and corrects the mismatch.
Fixing it :)
> Fix region mismatch in pytorch example

- ai-ml/ray/terraform/examples/pytorch/job/pytorch_submit.py
- ai-ml/ray/terraform/examples/xgboost/job/xgboost_submit.py
- website/docs/ai-ml/ray.md
This PR does two things.
1) Update the 'ray job logs' prompts at the end of the submit scripts for both pytorch and xgboost to include the --address arg.
2) Fix the port-forward ports on the pytorch example. We want locahost:8266 to forward to the pod at 8265.
Getting the docs to line up with the expected behavior
> Fix ray example docs

- streaming/flink/addons.tf
fix https://github.com/awslabs/data-on-eks/issues/200
> remove acl using bucket policy

- ai-ml/emr-spark-rapids/install.sh
- ai-ml/ray/terraform/install.sh
- analytics/terraform/datahub-on-eks/install.sh
- analytics/terraform/emr-eks-ack/install.sh
- analytics/terraform/emr-eks-fargate/install.sh
- analytics/terraform/emr-eks-karpenter/install.sh
- analytics/terraform/spark-k8s-operator/install.sh
- distributed-databases/cloudnative-postgres/install.sh
- streaming/flink/install.sh
- streaming/kafka/install.sh
- workshop/emr-eks/install.sh
The current implementation of the install scripts runs `terraform apply` 2 times per terraform module using -target. Additionally apply is run again 2 more times at the end of the script.
This means that we are running terraform apply twice as much as required.
This commit adds ` | tee /dev/tty` to all the apply steps so that the output can be captured and evaluated, as well as having the output print to screen. ${PIPESTATUS[0]} is used to check the return code of the first command.
> Reduce the number of times we run apply

- analytics/terraform/spark-k8s-operator/install.sh
- Update Spark install script to remove target apply on addons modules
- Pattern should deploy successfully and without error when using the `./install.sh` script
> fix: Update Spark install script to remove target apply on addons modules

- analytics/terraform/emr-eks-karpenter/addons.tf
- analytics/terraform/emr-eks-karpenter/helm-values/kube-prometheus-amp-enable.yaml
- analytics/terraform/emr-eks-karpenter/helm-values/kube-prometheus.yaml
- Adds a new AMP datasource to Grafana datasources
- Fixes issues related to authentication
> fix: Added a fix for Grafana to use sigv4 authentication

- schedulers/terraform/self-managed-airflow/README.md
The doc link is broken. Updating to the correct doc.
> docs: Update link for self-managed-airflow

- analytics/terraform/spark-k8s-operator/examples/karpenter/ebs-storage-dynamic-pvc/taxi-trip-execute.sh
- analytics/terraform/spark-k8s-operator/examples/karpenter/nvme-ephemeral-storage/taxi-trip-execute.sh
- analytics/terraform/spark-k8s-operator/examples/karpenter/nvme-yunikorn-gang-scheduling/taxi-trip-execute.sh
Minor fix to expect the correct number of arguments in the script that loads the taxi data to s3 bucket.
> fix: Expect correct number of arguments in the taxi data loader script

- analytics/terraform/datahub-on-eks/README.md
- analytics/terraform/datahub-on-eks/variables.tf
- analytics/terraform/emr-eks-karpenter/README.md
- analytics/terraform/emr-eks-karpenter/variables.tf
- analytics/terraform/spark-k8s-operator/README.md
- analytics/terraform/spark-k8s-operator/variables.tf
- streaming/flink/README.md
- streaming/flink/variables.tf
The `enable_vpc_endpoints` variable type in this repo is set as string type. This value is passed to the [vpc endpoint module ](https://registry.terraform.io/modules/terraform-aws-modules/vpc/aws/latest/submodules/vpc-endpoints#input_create)and [the security group module](https://registry.terraform.io/modules/terraform-aws-modules/security-group/aws/5.1.0#conditional-creation)'s `create` input variable. In both modules, this variable is defined as bool, not string. 
The default values for the variable is already correctly set as `false`. 
Fix incorrect types.
> fix: Correct vpc endpoint terraform variable type

- ai-ml/jark-stack/terraform/addons.tf
Sets `enableServiceMutatorWebhook` to `false` in Load Balancer because to work around the ordering issue as observed in  https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/issues/233. Another possible workaround is to use an Ingress but this seems good enough for this blueprint.
Noticed an internal error on install as seen in https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/issues/233
> fix: Disable service mutation webhook when deploying LBC in jark-stack

- ai-ml/jupyterhub/helm/karpenter-resources/templates/aws-node-template.yaml
Add a check in helm template to use the right `deviceName` in `awsnodetemplate`.
> fix: Adds a conditional to check for amiFamily to use the right deviceName

- ai-ml/jupyterhub/addons.tf
Uses correct instance family in the karpenter provisioner for Trainium instances.
> fix: Use correct instanceFamily for Trainium

- website/docs/gen-ai/inference/Llama2.md
> docs:  Fix doc for trainium-inferentia

- ai-ml/trainium-inferentia/addons.tf
- ai-ml/trainium-inferentia/variables.tf
I have added MPI Operator installation. The goal is to use MPI Operator to run allreduce-style distributed training on Amazon EKS.
I am working on a blog that leverages MPI operator for distributed training.
- [ Yes] Yes, I have tested the PR using my local account setup (Provide any test evidence report under Additional Notes)
- [ No] Mandatory for new blueprints. Yes, I have added a example to support my blueprint PR
- [ No] Mandatory for new blueprints. Yes, I have updated the `website/docs` or …
> feat: MPI operator installation code for distributed training use case

- website/docs/blueprints/distributed-databases/cloudnative-postgres.md
Remove redundant space.
This is a wee docs update. Just removing a space in one of the bash commands. 
Fixing typo.
> docs: Fix typo

- website/docs/bestpractices/networking/networking.md
Minor fix to remove duplicate CIDR range
> docs: Change duplicate 100.65.0.0/16 to 100.66.0.0/16

- streaming/kafka/examples/kafka-producers-consumers.yaml
- streaming/kafka/examples/kafka-topics.yaml
- streaming/kafka/helm-values/strimzi-kafka-values.yaml
- streaming/kafka/install.sh
- streaming/kafka/kafka-manifests/kafka-cluster.yaml
- streaming/kafka/kafka-manifests/kafka-rebalance.yaml
- streaming/kafka/main.tf
Add a new examples
Add Kafka cruise control
Update Kafka version
For Kafka blog post
> chore: Update Kafka blueprint

- ai-ml/jupyterhub/cleanup.sh
Fixes https://github.com/awslabs/data-on-eks/issues/381
Adds VPC to the cleanup script
Bringing the cluster up and down, I noticed a build-up of VPCs, which ended up causing my `nodeclaim` issue (and spending unnecessary $):
```
`creating instance, with fleet error(s), InvalidParameter: Security group sg-063f3ce9c9129f915 and subnet subnet-03c6b3adbd7c25760 belong to different networks.; InvalidParameter: Security group sg-063f3ce9c9129f915 and subnet subnet-0355df2dfc137557b belong to different networks.
```
I cleaned up those VPCs by hand (which was a little tedious), brought the cluster down, and I think `./cleanup.sh` has actually cleaned up.
> fix: Cleanup VPC as when cleaning jupyterhub

- streaming/flink/addons.tf
Update Flink operator version to 1.7.0 as 1.4.0 is no longer available and fails to deploy.
> fix: [Flink] - Push operator version to 1.7.0 as 1.4.0 is unavailable

- website/docs/blueprints/ai-ml/ray.md
Corrects simple typo - "kuebctl" was present in the Ray doc
```bash
-kuebctl get nodes
+kubectl get nodes
```
Just simple cleanup
> Fixed type for kubectl

- website/docs/blueprints/ai-ml/ray.md
This PR provides clarity for the verification steps for installing Ray. (It is currently confusing as the output does not match the command suggested)
Command given
```
kubectl get pods -n kuberay-operator
```
output provided
```
NAMESPACE            NAME                               READY   STATUS    RESTARTS        AGE
amazon-cloudwatch    aws-cloudwatch-metrics-d4xrr       1/1     Running   1 (1h37m ago)   1h
amazon-cloudwatch    aws-cloudwatch-metrics-tpqsz       1/1     Running   1 (1h37m ago)   1h
....
```
As you can see the output is showing other namespaces (the output from `kubectl get pods -A` likely.
Consult the …
> Aligned provided output to match the command shown (Ray install validation)

- schedulers/terraform/managed-airflow-mwaa/dags/example_emr_eks_new.py
The EMR containers demo dag `emr_eks_pi_job` does not load on MWAA with the error below. This is even before adding the `emr_eks` connection.
`Error when trying to pre-import module 'airflow.providers.amazon.aws.operators.emr_containers' found in /usr/local/airflow/dags/example_emr_eks_new.py: No module named 'airflow.providers.amazon.aws.operators.emr_containers'`
This is because the import does not follow package structure for AWS provider version [7.1.0](https://airflow.apache.org/docs/apache-airflow-providers-amazon/7.1.0/_api/airflow/providers/amazon/aws/operators/emr/index.html) which is the one [installed with Airflow v2.5.1 on MWAA](https://docs.aws.amazon.com/mwaa/latest/userguide/connections-packages.html#connections-packages-table-251).
This fix updates the EMR container …
> Fixed EMR container operator import

- schedulers/terraform/managed-airflow-mwaa/eks.tf
This PR closes issue #312. 
It updates the EKS security group rule to allow traffic to control plane (port 443) from MWAA security group.
Building on top of this code for my own project.
- [x ] Yes, I have tested the PR using my local account setup (Provide any test evidence report under Additional Notes)
- [ x] Yes, I ran `pre-commit run -a` with this PR. Link for installing [pre-commit](https://pre-commit.com/) locally
> closes #312 Allow access to EKS cluster from MWAA security group

- analytics/terraform/emr-eks-karpenter/README.md
- analytics/terraform/emr-eks-karpenter/addons.tf
- analytics/terraform/emr-eks-karpenter/examples/benchmark/tpcds-benchmark-1t.yaml
- analytics/terraform/emr-eks-karpenter/examples/benchmark/tpcds-benchmark-data-generation-1t.yaml
- analytics/terraform/emr-eks-karpenter/examples/nvme-ssd/karpenter-compute-provisioner/driver-pod-template.yaml
- analytics/terraform/emr-eks-karpenter/examples/nvme-ssd/karpenter-compute-provisioner/execute_emr_eks_job.sh
- analytics/terraform/emr-eks-karpenter/examples/nvme-ssd/karpenter-compute-provisioner/executor-pod-template.yaml
- analytics/terraform/emr-eks-karpenter/examples/nvme-ssd/karpenter-graviton-memory-provisioner/driver-pod-template.yaml
- analytics/terraform/emr-eks-karpenter/examples/nvme-ssd/karpenter-graviton-memory-provisioner/executor-pod-template.yaml
- analytics/terraform/emr-eks-karpenter/examples/nvme-ssd/karpenter-memory-provisioner/driver-pod-template.yaml
- analytics/terraform/emr-eks-karpenter/examples/nvme-ssd/karpenter-memory-provisioner/executor-pod-template.yaml
- analytics/terraform/emr-eks-karpenter/examples/nvme-ssd/karpenter-yunikorn-gangscheduling/driver-pod-template.yaml
- analytics/terraform/emr-eks-karpenter/examples/nvme-ssd/karpenter-yunikorn-gangscheduling/executor-pod-template.yaml
- analytics/terraform/emr-eks-karpenter/karpenter-provisioners/spark-compute-optimized-provisioner.yaml
- analytics/terraform/emr-eks-karpenter/karpenter-provisioners/spark-graviton-memory-optimized-provisioner.yaml
- analytics/terraform/emr-eks-karpenter/karpenter-provisioners/spark-memory-optimized-provisioner.yaml
- analytics/terraform/emr-eks-karpenter/main.tf
- analytics/terraform/emr-eks-karpenter/variables.tf
- website/docs/blueprints/amazon-emr-on-eks/emr-eks-karpenter.md
- Updated EMR on EKS blueprint to incorporate the latest Karpenter version (helm.sh/chart: karpenter-v0.32.1).
- Adjusted examples to utilize RAID0 configuration set by the bootstrap command. The examples now utilize emptyDir instead of hostPath for storing shuffle data.
- Added information: Karpenter userdata uses the bootstrap commands to configure the RAID0. The same RAID0 disk is used for containerd, kubelet, and pod logs.
- Updated documentation.
- Removed the ALB controller as it is no …
> feat: EMR on EKS Blueprint upgrade with Karpenter v0.32.1

- ai-ml/trainium-inferentia/examples/dp-bert-large-pretrain/1-bert-pretrain-build-image.sh
- ai-ml/trainium-inferentia/examples/dp-bert-large-pretrain/docker/Dockerfile.bert_pretrain
- ai-ml/trainium-inferentia/examples/dp-bert-large-pretrain/lib/trn1_dist_ddp.py
Corrects a few issues with the BERT pretraining / trn1 example
- adds missing Volcano queue
- pins Neuron version to 2.16.1 to avoid CCOM timeouts
- adjusts torchx entrypoint / args to avoid 'filename too long' errors
User reported an issue with this example
Tested 2-node jobs using both trn1.32xl and trn1n.32xl
> Fix BERT pretraining trn1 example

- streaming/flink/addons.tf
- streaming/flink/examples/karpenter/flink-sample-job.yaml
- streaming/flink/karpenter-provisioners/flink-compute-optimized-provisioner.yaml
- streaming/flink/karpenter-provisioners/flink-graviton-memory-optimized-provisioner.yaml
- streaming/flink/karpenter-provisioners/flink-memory-optimized-provisioner.yaml
- streaming/flink/main.tf
Upgrade Karpenter version for Flink Blueprint
> feat: Flink blueprint upgrade to latest Karpenter

- .gitignore
- ai-ml/trainium-inferentia/eks.tf
This is a fix for issue 429 - "Unable to deploy llama2 on Eks/Ray Serve/inf2"
1. Changed the core instance type to m5.2xlarge since the rayhead pod was not getting scheduled due to lack of memory
2. Changed the inf2.24xlarge instance type to ondemand since those seem to be more appropriate for a chat application workload
3. fixed the label on inf2.24xlarge and inf2.48xlarge  node so that the ray serve pod could find it
I could not complete the tutorial as it is outlined here -> …
> fix: For issue 429 "Unable to deploy llama2 on Eks/Ray Serve/inf2"

- website/docs/gen-ai/index.md
Remove broken links in gen ai doc overview page
Remove broken links in gen ai doc overview page
> fix: Remove broken links in gen ai doc overview page

- ai-ml/ray/terraform/modules/ray-cluster/main.tf
Update ray-cluster karpenter_provisioner  capacity-type to on-demand
The Karpenter Provisioner created for the Ray on EKS xgboost example is set to use a "spot" capacity-type, which failed to provision the required additional node. As a result, the the xgboost head node pods got stuck in a pending state. After changing the capacity-type to on-demand, a new M5a.4xlarge instance was successfully deployed and added to the ray-cluster as a node, allowing the xgboost head node pods to run.
> fix: Update ray-cluster karpenter_provisioner capacity-type to on-demand

- ai-ml/mlflow/addons.tf
- ai-ml/mlflow/eks.tf
Upgrade Karpenter version for MLflow blueprint
[#411](https://github.com/awslabs/data-on-eks/issues/411)
> feat: MLflow blueprint upgrade to latest Karpenter

- ai-ml/jupyterhub/addons.tf
I had an old version of https://github.com/jupyterhub/oauthenticator that broke my custom auth. On closer inspection we aren't even using a GA release of the jhub helm chart.
```
$ helm list --namespace jupyterhub
NAME      	NAMESPACE 	REVISION	UPDATED                                	STATUS  	CHART                  	APP VERSION
efs       	jupyterhub	1       	2024-03-15 16:26:51.545097674 -0400 EDT	deployed	efs-0.0.1              	0.0.1      
efs-shared	jupyterhub	1       	2024-03-15 …
```
> feat: Override eks_data_addons jupyterhub chart version default

- website/docs/gen-ai/excalidraw/stable-diffusion-inf2.excalidraw
Adds excalidraw architecture diagram for the stable diffusion blueprint on Inf2. 
Adds excalidraw architecture diagram for the stable diffusion blueprint on Inf2. 
Currently, there's no folder to store the excalidraw projects. This PR adds a folder in the gen-ai section of the doc website to store excalidraw project files for the stable-diffusion-inf2 blueprint. Similarly, we can add other excalidraw projects to this folder.
> feat: Add architecture diagram in doc website for stable-diffusion-inf2 blueprint

- .gitignore
- analytics/terraform/spark-k8s-operator/examples/benchmark/tpcds-benchmark-3t.yaml
- analytics/terraform/spark-k8s-operator/examples/benchmark/tpcds-benchmark-data-generation-3t.yaml
- analytics/terraform/spark-k8s-operator/examples/karpenter/nvme-ephemeral-storage/nvme-ephemeral-storage.yaml
- website/docs/blueprints/data-analytics/_compute_optimized_nodepool.md
- website/docs/blueprints/data-analytics/_graviton_nodepool.md
- website/docs/blueprints/data-analytics/_memory_optimized_nodepool.md
- website/docs/blueprints/data-analytics/_replace_s3_bucket_placeholders.mdx
- website/docs/blueprints/data-analytics/_taxi_trip_exec.md
- website/docs/blueprints/data-analytics/spark-operator-yunikorn.md
This pull request adds much needed details to the spark operator page.
1. It is now clear where to find the S3 Bucket that is created.
2. All `cd ...` commands now use an environment variable called DOEKS_HOME that ensures copy and paste always works in every example.
3. Example `sed` commands are provided for replacing the S3_BUCKET placeholders in scripts and spark application yaml manifests.
4. All s3 bucket placeholders in the examples have been unified to use <S3_BUCKET> in every file.
Some quality of life changes as well.
Using Docusaurus partials for paragraphs that are repeated throughout examples.
Move large yaml examples out of the single markdown file into their own partials.
The spark on EKS examples are currently very terse. Many assumptions were being made on what the user …
> docs: Spark operator updates

- .github/workflows/codespell.yml
The current codespell workflow checks fail on .excalidraw file which should be checked for spellings. This PR skips those files from being spellchecked.
> chore: Update codespell.yml to skip excalidraw files

- schedulers/terraform/argo-workflow/README.md
- schedulers/terraform/argo-workflow/variables.tf
- schedulers/terraform/argo-workflow/workflow-examples/sensor-sqs-sparkjobs.yaml
- schedulers/terraform/argo-workflow/workflow-examples/sparkapp-graviton.yaml
- schedulers/terraform/argo-workflow/workflow-examples/taxi-trip-execute.sh
The Argo Workflow example now runs Spark jobs in parallel on x86 and Graviton instances.
Updated to latest EKS version.
> feat: Modified example to run multiArch Spark jobs in parallel

- ai-ml/trainium-inferentia/examples/inference/ray-serve/stable-diffusion-inf2/ray-service-stablediffusion.yaml
- ai-ml/trainium-inferentia/examples/inference/ray-serve/stable-diffusion-inf2/ray_serve_stablediffusion.py
Creates docker image `ray2.9.0-py310-stablediffusion-neuron` with tag `latest`
Passes Model Id as RayServe configuration and removes hardcoded model_id from inference script
> feat: Update stable-diffusion-neuron docker image

- .codespellrc
- .pre-commit-config.yaml
Added excalidraw to codespell ignore
Remove terraform validate from pre-commit, developers should run this themselves.
Terraform validate in the precommit takes absolutely forever on the root of the project. Everyone is skipping it or aborting it. So let's remove it.
Finally, excalidraw always comes up in spelling check output. Let's add that to ignore.
- [x ] Yes, I have tested the PR using my local account setup (Provide any test evidence report under Additional Notes)
- [x ] Yes, I ran `pre-commit run -a` with this PR. Link for installing [pre-commit](https://pre-commit.com/) locally
> chore: Clean up pre-commit warnings and delays

- .codespellrc
- .pre-commit-config.yaml
Reverts awslabs/data-on-eks#491
reverting this PR as the pre-commit validate is failing and looking for this hook
Check the results here
https://github.com/awslabs/data-on-eks/actions/runs/8835984927/job/24271524130?pr=485
> chore: Revert "chore: Clean up pre-commit warnings and delays"

- ai-ml/mlflow/addons.tf
- ai-ml/trainium-inferentia/addons.tf
- analytics/terraform/emr-eks-karpenter/addons.tf
- analytics/terraform/spark-k8s-operator/addons.tf
- distributed-databases/trino/addons.tf
- schedulers/terraform/argo-workflow/addons.tf
The bucket arns for several `aws_for_fluentbit`  addons have an extra `}` at the end, resulting in fluentbit unable to write logs to s3.
❤️
> fix: Remove trailing curly from wildcard bucket arn

- .github/workflows/plan-examples.yml
> chore: Remove pull_request_target from plan examples workflow

- gen-ai/inference/stable-diffusion-rayserve-gpu/Dockerfile
In Inference module, within Stable diffusion on GPU blueprint, RayServe FastAPI function is of different name than that of what's in pre-built image. So either file name for RayServe script has to be changed to that of what's in Docker image in Public ECR DoEKS repository or Dockerfile needs to be changed to reference right script name. This PR is intended to take latter approach in modifying Dockerfile, so users using blueprint will be able to build own image that references correct script  …
> fix: RayServe script name mismatch in Dockerfile

- website/docs/blueprints/ai-ml/trainium.md
… Trainium on EKS Blueprint #533
There is a typo in the following commands on the Blueprint for AWS Trainium on EKS:
https://awslabs.github.io/data-on-eks/docs/blueprints/ai-ml/trainium
The wrong commands are:
chomd +x 1-bert-pretrain-build-image.sh
chomd +x 2-bert-pretrain-precompile.sh
The correct version should be:
chmod +x 1-bert-pretrain-build-image.sh
chmod +x 2-bert-pretrain-precompile.sh
I'm part of the AWS Container TFC and a Solution Architect working with customers promoting this …
> fix: Incorrect command to provide Linux permission on the AWS Trainium on EKS Blueprint #533

- ai-ml/trainium-inferentia/addons.tf
- ai-ml/trainium-inferentia/eks.tf
1. In MNGs we were adding karpenter tags which was not necessary
2. Security group IDs were missing in karpenter helm config
3. Removed karpenter tags for 100.x subnets
4. Default Nodepool and Inferentia-inf2 nodepools were not getting created before the above fixes resolved the issue.
- [Yes ] Yes, I have tested the PR using my local account setup (Provide any test evidence report under Additional Notes)
- [ Yes] Mandatory for new blueprints. Yes, I have added a example to support my blueprint PR …
> feat: tags + security group and karpenter helm config updates

- analytics/terraform/spark-k8s-operator/README.md
- analytics/terraform/spark-k8s-operator/addons.tf
- analytics/terraform/spark-k8s-operator/helm-values/aws-for-fluentbit-values.yaml
- analytics/terraform/spark-k8s-operator/helm-values/spark-operator-values.yaml
- analytics/terraform/spark-k8s-operator/spark-team.tf
- analytics/terraform/spark-k8s-operator/variables.tf
- Added support for creating multiple teams. By default, it creates spark-team-a, spark-team-b, and spark-team-c, all of which use the same IAM policies. However, you can modify the code to customize the policies if needed.
- Updated Fluent Bit configuration to write Spark logs to a dedicated folder structure in the S3 bucket.
- Upgraded the blueprint to use EKS version 1.30.
- Upgraded the Spark Operator to the latest version.
> feat: Upgrade Spark operator blueprint to EKS 1.30 and fluent-bt changes

- .gitignore
- ai-ml/trainium-inferentia/elastic-cache-redis.tf
- website/package-lock.json
- website/package.json
This PR addresses security vulnerabilities in the ws package used by Docusaurus dependencies.
Issues Addressed:
Issue #53: ws affected by a DoS when handling a request with many HTTP headers.
Conflicting dependencies: @docusaurus/core@3.0.1, @docusaurus/preset-classic@3.0.1, and docusaurus-lunr-search@3.3.1.
Current ws version: 7.5.10
Fixed version: 8.17.1 (not currently compatible with existing dependencies).
Issue #52: ws affected by a DoS vulnerability.
Same conflicting dependencies and fixed …
> fix: Dependabot Security Alert Fix for Docusaurus Packages

- website/docs/blueprints/data-analytics/observability-spark-on-eks.md
Fix code block for config spark application yaml
Improve documentation
> fix: Add yaml code block in documentation prometheus section

- ai-ml/nvidia-triton-server/addons.tf
- ai-ml/nvidia-triton-server/helm-values/prometheus-adapter.yaml
- ai-ml/nvidia-triton-server/nvidia-triton-server.tf
Add custom metrics based scaling for NVIDIA Triton server
Closes #569
> feat: Add custom metrics based scaling for NVIDIA Triton server

- ai-ml/nvidia-triton-server/nvidia-triton-server.tf
One of the recent PRs introduced an error(see below) causing the model loading to fail when the triton server gets deployed.
```text
Error Log:
I0715 04:06:56.609115 1 server.cc:674] 
+-----------+---------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Model     | Version | Status                                                                                                                                                                                                        |
+-----------+---------+--------------------------------------------------------------------------------------------------------------------------------- …
```
> fix: Fix Triton server model loading error

- ai-ml/jark-stack/terraform/cleanup.sh
- ai-ml/nvidia-triton-server/cleanup.sh
Removes the need for prompting the user to enter region.
> fix: Update cleanup script

- gen-ai/inference/llama2-13b-chat-rayserve-inf2/ray-service-llama2.yaml
- gen-ai/inference/llama3-8b-instruct-rayserve-inf2/ray-service-llama3.yaml
- gen-ai/inference/mistral-7b-rayserve-inf2/ray-service-mistral-ft.yaml
- gen-ai/inference/mistral-7b-rayserve-inf2/ray-service-mistral.yaml
- gen-ai/inference/stable-diffusion-xl-base-rayserve-inf2/ray-service-stablediffusion.yaml
- website/docs/gen-ai/inference/Mistral-7b-inf2.md
Adds neuron-scheduler for Ray head and worker Pods in AWS Neuron gen ai patterns
We're deploying [my-scheduler.yml](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/_downloads/e739253083129abeaf6f6ad1db7ccb21/my-scheduler.yml) and [k8s-neuron-scheduler-eks.yml](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/_downloads/e518187532701b6660dcd70ea28c2562/k8s-neuron-scheduler-eks.yml) in our trainium-inferentia blueprint.
As part of this PR, we are updating the Ray Service yamls to set …
> feat: Neuron scheduler update for trainium-inferentia blueprints

- ai-ml/trainium-inferentia/addons.tf
- ai-ml/trainium-inferentia/variables.tf
Add a variable to accept and configure access_entries for the cluster.
Mainly used for the workshop. We need a way to add IDE access to EKS cluster.
> chore: Add access entry for workshop

- ai-ml/trainium-inferentia/addons.tf
- ai-ml/trainium-inferentia/eks.tf
This PR fixes an issue where we need to provision access entry policies. I reverted the karpenter access entry to what it was before and instead now just pass the `var.access_entries` params to the EKS module as is. The EKS module has a way to accept both entries and policies in one single block.
> fix: Use eks module for access_entries for trn-inf blueprint

- ai-ml/nvidia-triton-server/README.md
- ai-ml/nvidia-triton-server/addons.tf
- ai-ml/trainium-inferentia/addons.tf
- website/docs/blueprints/ai-ml/trainium.md
- website/docs/gen-ai/inference/GPUs/vLLM-NVIDIATritonServer.md
Adds cloudwatch eks add on with enhanced container insights monitoring for neuron
The Neuron Monitor container solution provides a comprehensive monitoring framework for ML workloads on Amazon EKS, using the power of Neuron Monitor. This PR adds cloudwatch eks add on to the trainium-inferentia blueprint with …
> feat: Add cloudwatch eks add on with enhanced monitoring for neuron

- gen-ai/inference/vllm-llama3.1-405b-trn1/gradio-client.yaml
Updates the sample prompt for Llama3.1-405b model inference
> feat: Update gradio client with sample prompt for Llama3.1-405b model inference

- analytics/terraform/spark-k8s-operator/README.md
- analytics/terraform/spark-k8s-operator/addons.tf
- analytics/terraform/spark-k8s-operator/helm-values/kube-prometheus-amp-enable.yaml
- analytics/terraform/spark-k8s-operator/helm-values/kube-prometheus.yaml
- analytics/terraform/spark-k8s-operator/helm-values/kubecost-values.yaml
Adding a storage class for encrypted gp3 volumes and making it the default, then updating the addons to use that `gp3` storage class for PVCs.
bringing parity between the ipv4 and ipv6 versions of the spark operator blueprint
> feat: Spark operator default to encrypted gp3 PVs

- analytics/terraform/spark-eks-ipv6/spark-team.tf
- analytics/terraform/spark-k8s-operator/spark-team.tf
Create a unique name for the spark job execution IRSA policy by using `name_prefix` instead of `name`. 
solves https://github.com/awslabs/data-on-eks/issues/668
If you deploy the solution with the same name and account but different regions, the name of this policy conflicts and blocks the creation.
this could just as easily be avoided by not using the same name in the variables for the solution.
> feat: Use unique name for the spark job execution IRSA policy

- ai-ml/emr-spark-rapids/README.md
- ai-ml/nvidia-triton-server/README.md
- ai-ml/trainium-inferentia/addons.tf
- ai-ml/trainium-inferentia/eks.tf
- analytics/terraform/datahub-on-eks/README.md
- analytics/terraform/emr-eks-ack/README.md
- analytics/terraform/emr-eks-fargate/README.md
- analytics/terraform/emr-eks-karpenter/README.md
- analytics/terraform/spark-k8s-operator/README.md
- schedulers/terraform/argo-workflow/README.md
- schedulers/terraform/aws-batch-eks/README.md
- schedulers/terraform/self-managed-airflow/README.md
- streaming/flink/README.md
- streaming/kafka/README.md
- streaming/nifi/README.md
- streaming/spark-streaming/terraform/README.md
1. Updates to use official neuron helm chart (data add-ons repo has separate [PR](https://github.com/aws-ia/terraform-aws-eks-data-addons/pull/46) to do this. Please approve this first, will update module source to new version then.
2. Update to karpenter v1, use upstream EKS module to deploy karpenter resources then use helm chart resource to deploy karpenter controller.
Fixes #686
> feat: Use official neuron helm chart for device plugin and scheduler

- analytics/terraform/spark-k8s-operator/README.md
- analytics/terraform/spark-k8s-operator/addons.tf
- analytics/terraform/spark-k8s-operator/eks.tf
- analytics/terraform/spark-k8s-operator/variables.tf
- analytics/terraform/spark-k8s-operator/versions.tf
This PR updates the EKS terraform module to bring in support for NodeADM bootstrapping. 
it also updates the IAM configuration for Karpenter to use `access_entries` instead of `aws_auth_roles`. 
#688 added MNG using AL2023 AMIs which require newer Bootstrapping:
```
cloudinit_pre_nodeadm = [
{
content_type = "application/node.eks.aws"
content      = <<-EOT
---
apiVersion: node.eks.aws/v1alpha1
kind: NodeConfig
spec:
instance:
localStorage:
strategy: RAID0
EOT
}
]
```
This `cloudinit_pre_nodeadm` property isn't supported in version 19.x of the EKS terraform module, and the aws_auth entries we use are removed in 20.x+ 
I was able to check the ephemeral storage thats being returned from the `spark_benchmark_ssd` 
```
Capacity:
cpu:                48
ephemeral-storage:  1756689344Ki …
```
> fix: Update EKS module to support AL2023 bootstrapping

- ai-ml/trainium-inferentia/addons.tf
Fixes a bug in the trainium-inferentia blueprint where it fails to cleanly install due to karpenter-resources being applied before karpenter helm chart is deployed by adding an implicit dependency.
> fix: Add implicit dependecy for karpenter resources

- analytics/terraform/spark-k8s-operator/examples/benchmark/tpcds-benchmark-1t-ebs.yaml
- analytics/terraform/spark-k8s-operator/examples/benchmark/tpcds-benchmark-1t-ssd.yaml
- analytics/terraform/spark-k8s-operator/examples/benchmark/tpcds-benchmark-data-generation-1t.yaml
- analytics/terraform/spark-k8s-operator/examples/docker/Dockerfile-benchmark
- analytics/terraform/spark-k8s-operator/helm-values/kube-prometheus-amp-enable.yaml
- analytics/terraform/spark-k8s-operator/helm-values/kube-prometheus.yaml
increases the observability for the spark benchmark jobs:
- enable spark metrics and eventlogging on the benchmark jobs
- add a PodMonitor config to the kube-prometheus-stack to scrape the metrics 
- cleanup the dockerfile to avoid a warning on build
As we've been running benchmarks the increased visibility has helped compare performance between runs.
> feat: Spark benchmark observability

- analytics/terraform/spark-k8s-operator/vpc.tf
Adds the public subnet CIDR blocks to the security group on the VPC endpoints and adds the S3 gateway endpoint to the Public route table. 
I launched an instance in the Spark operator VPC to use as a bastion instance and selected the Public subnets but the SSM agent on the instance never connected. I think when the vpc endpoints are enabled, the SSM endpoint overrides the DNS for the service, but the Security group blocks traffic from the public subnet.
This shouldn't cause a problem for our examples/eks nodes as we don't really leverage the Public subnet but was annoying to debug.
> fix: Add all VPC CIDRs to VPCe config

- website/docs/blueprints/data-analytics/spark-eks-ipv6.md
- website/docs/blueprints/troubleshooting/troubleshooting.md
Adds a section in the blueprints troubleshooting describing how to create the IPv6 policy for EKS.
The spark IPv6 blueprint fails to deploy if the AmazonEKS_CNI_IPv6_Policy doesn't exist to attach to IAM roles with the error below: 
```
Error: attaching IAM Policy (arn:aws:iam::1234567890:policy/AmazonEKS_CNI_IPv6_Policy) to IAM Role (core-node-group-eks-node-group-20241111182906854800000003): operation error IAM: AttachRolePolicy, https response error StatusCode: 404, RequestID: 9c99395a-ce3d-4a05-b119-538470a3a9f7, NoSuchEntity: Policy arn:aws:iam::1234567890:policy/AmazonEKS_CNI_IPv6_Policy does not exist or is not attachable.
```
> docs: Troubleshooting section for IPv6 policy

- analytics/terraform/spark-eks-ipv6/install.sh
Removes an extra read statement that breaks the install script for the v6 spark solution.
> fix: Update spark ipv6 install.sh

- website/docs/blueprints/ai-ml/jark.md
Corrected the path for install.sh and cleanup.sh files. 
In addition, Added instructions on how to use AWS Profile name for authentication
- [ x] Yes, I have tested the PR using my local account setup (Provide any test evidence report under Additional Notes)
> chore: Corrected paths for install.sh/cleanup.sh commands in jark.md

- analytics/terraform/spark-k8s-operator/examples/s3-tables/s3table-spark-operator.yaml
- streaming/flink/README.md
- streaming/flink/addons.tf
- streaming/flink/versions.tf
Fixes Flink operator blueprint deployment errors
> fix: Flink operator blueprint deployment errors

- analytics/terraform/spark-k8s-operator/addons.tf
- analytics/terraform/spark-k8s-operator/helm-values/kube-prometheus-amp-enable.yaml
- analytics/terraform/spark-k8s-operator/helm-values/kube-prometheus.yaml
Enables the prometheus PodMonitor creation in the spark-operator helm chart and updates the prometheus config to pick up monitors across namespaces (`kube-prometheus-stack`, is the default)
as we continue benchmarks/testing having visibility into the operator performance will help us understand the performance
> feat: Enable spark-operator prometheus metrics 

- analytics/terraform/spark-k8s-operator/addons.tf
This disables the monitoring for Spark-operator by default to address #740
The change to enable these metrics broke the deployment of the solution
> fix: Disable spark-operator podmonitor

- analytics/terraform/spark-k8s-operator/examples/benchmark/scale/kubeflow-spark-operator-dashboard.json
- analytics/terraform/spark-k8s-operator/examples/benchmark/scale/scale-test-results-grafana.json
Adds Grafana dashboard for kubeflow Spark Operator.
Combines relevant k8s API server metrics, Spark Application and WorkQueue metrics into one dashboard.
> feat: Add Grafana dashboard for kubeflow Spark Operator

- analytics/terraform/emr-eks-fargate/examples/basic-pyspark-job.sh
EMR virtual cluster id variable name incorrectly had extra `EMR_`.
> style: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)

- website/docs/gen-ai/inference/GPUs/vLLM-NVIDIATritonServer.md
Documentation was not on par with actual cluster that was created from instructions, namespace `kube-prometheus-stack` didn't exist, but commands worked as expected using namespace `monitoring`
```
$ kubectl get svc -n triton-vllm
NAME                                                   TYPE        CLUSTER-IP …
```
> docs: NVIDIA triton server monitoring namespace fix

- analytics/terraform/spark-k8s-operator/README.md
- analytics/terraform/spark-k8s-operator/addons.tf
- analytics/terraform/spark-k8s-operator/amp.tf
- analytics/terraform/spark-k8s-operator/eks.tf
- analytics/terraform/spark-k8s-operator/spark-team.tf
- analytics/terraform/spark-k8s-operator/vpc.tf
Updates the Terraform modules and Helm charts to the latest available. 
Modules
- aws-ia/eks-data-addons/aws 1.34 -> 1.35
- aws-ia/eks-blueprints-addons/aws ~>1.2 -> ~>1.20
- terraform-aws-modules/s3-bucket/aws ~>3.0 -> ~>4.6
- terraform-aws-modules/eks/aws ~>20.26 -> ~>20.33
- aws-ia/eks-blueprints-addon/aws ~>1.0 -> ~>1.1 (Spark team IRSA)
- terraform-aws-modules/vpc/aws ~>5.0 -> ~>5.19
- terraform-aws-modules/security-group/aws ~>5.0 -> ~>5.3
- terraform-aws-modules/vpc/aws//modules/vpc-endpoints ~>5.0 -> ~>5.19
- terraform-aws-modules/iam/aws//modules/iam-role-for-service-accounts-eks ~>5.34 > ~>5.52
Helm chart versions
- spark-operator 2.0.1 -> 2.1.0 
- yunikorn 1.6.0 -> 1.6.1 
- aws-ebs-csi-driver default -> most_recent
- coredns default -> most_recent
- vpc-cni default -> …
> chore: Spark blueprint version bump

- analytics/terraform/spark-k8s-operator/examples/s3-tables/s3table-duckdb-demo.ipynb
This adds an example of using S3 Tables with Spark and DuckDB in a Jupyter Notebook.
The current example is bare and need more expanding.
> feat: Add an example notebook for S3 Tables

- ai-ml/bionemo/examples/esm1nv/esm1nv_pretrain-job.yaml
- ai-ml/bionemo/examples/esm2nv/esm2nv-training-job.yaml
- website/docs/ai/training/GPUs/bionemo.md
following changes has been made in this PR to resolve inconsistencies on the this website page
https://awslabs.github.io/data-on-eks/docs/gen-ai/training/GPUs/bionemo
1) Default region us-west-2 mentioned in website has been changes to us-east-1 as declared in variable.tf.
2) Reference for p3.16xlarge instances in the website has been updated to g5.12xlarge instance.
3) We are using "nprocPerNode" to "4 in pre-training jobs and same has been updated on the website instead of 8. 
4) We can not directly run nvidia-smi on bottlerocket OS nodes. Same has been updated now to run inside pod to get GPU status snapshot of the worker node on which pod is running.
5) added nodeSelector term in pre-training jobs to get pods schedule on g5.12xlarge instances..
> fix: Bionemo module doc changes

- analytics/scripts/order-execute.sh
This is to generate multiple input files for the Spark workshop labs. The current 7M records file wasn't sufficient enough to make jobs run longer. This PR would copy the same file four times so making it 25M+ records for the labs.
> fix: Generate multiple input files for spark workshop

- analytics/terraform/spark-k8s-operator/addons.tf
- analytics/terraform/spark-k8s-operator/examples/karpenter/spark-app-graviton.yaml
- analytics/terraform/spark-k8s-operator/examples/karpenter/spark-app-nvme.yaml
- analytics/terraform/spark-k8s-operator/examples/karpenter/spark-app-spot-cmr.yaml
- analytics/terraform/spark-k8s-operator/examples/karpenter/spark-app-spot-r.yaml
Spark on eks workshopUpdated the Labs 2 through 5 to run the Spark drivers on EC2 on-demand instances.
EC2 Spot best practices for running Spark workloads is to schedule the Spark drivers on EC2 On-Demand and schedule the Spark executors on a mix of EC2 mOn-Demand and Spot instances. This PR adds a following:
- A …
> fix: Updated the Labs 2 thru 5 to run the Spark drivers on EC2 on-demand instances (Spark on eks workshop)

- analytics/terraform/spark-k8s-operator/examples/s3-tables/s3table-iceberg-pyspark.ipynb
- analytics/terraform/spark-k8s-operator/examples/s3-tables/s3table-iceberg-pyspark.py
This updates the S3 Tables examples to use Apache Iceberg REST APIs because this is now the recommended approach to using S3 Tables.
I would like to keep the examples in-line with recommendations.
> fix: Update s3tables examples to use iceberg rest catalog api

- analytics/terraform/spark-k8s-operator/addons.tf
- analytics/terraform/spark-k8s-operator/karpenter-sqs.tf
- analytics/terraform/spark-k8s-operator/main.tf
- analytics/terraform/spark-k8s-operator/variables.tf
This PR creates a SQS queue and node termination event rules for Karpenter. Karpenter requires these to be added so that it can forward interruption events from AWS services to the SQS queue for better node handling.
Issue #819
> feat: Add changes to include SQS interruption queue for Karpenter and related Event Bridge rules

- distributed-databases/cloudnative-postgres/README.md
- distributed-databases/cloudnative-postgres/resources.tf
- distributed-databases/trino/README.md
- distributed-databases/trino/main.tf
- website/docs/blueprints/distributed-databases/aerospike.md
Resolves issues with the Pre-commit checks on PRs that have come up. primarily:
- distributed-databases/trino/ has an extra data value: `data "aws_ecrpublic_authorization_token" "token" is declared but not used`
- distributed-databases/cloudnative-postgres looks to be trying to download an addons version thats broken: `error downloading 'https://github.com/aws-ia/terraform-aws-eks-blueprints-addons.git?ref=ed27abc%2F%2Fmodules%2Firsa'`
checks are failing on my PR 
I did not test these changes and the blueprints involved may have issues. However we should probably take an update pass on them anyway.
> chore: Fix pre-commit issues 

- website/docs/blueprints/data-analytics/_taxi_trip_exec.md
- website/docs/blueprints/data-analytics/spark-operator-yunikorn.md
- Added a sed command to update the S3_BUCKET placeholder in the pyspark-pi-job.yaml to succesfully run the SparkApplication
-  Added `./` in the `_taxi_trip_exec.md` for successful execution of the script
- The `pyspark-pi-job.yaml` execution fails as we are logging spark events in an S3 bucket …
> fix: Added and updated commands in the spark-yunikorn example for proper execution

- website/docs/blueprints/data-analytics/spark-operator-yunikorn.md
This fixes the website deployment issue by escaping the HTML tag properly. 
Here's an example of a failing job: https://github.com/awslabs/data-on-eks/actions/runs/15003304012/job/42221796341
> fix: Website build issue with html tag

- .github/workflows/pre-commit.yaml
- .pre-commit-config.yaml
- ai-ml/emr-spark-rapids/README.md
- ai-ml/nvidia-triton-server/README.md
- ai-ml/ray/terraform/README.md
- analytics/terraform/datahub-on-eks/README.md
- analytics/terraform/emr-eks-ack/README.md
- analytics/terraform/emr-eks-ack/modules/emr-ack/README.md
- analytics/terraform/emr-eks-fargate/README.md
- analytics/terraform/emr-eks-karpenter/README.md
- analytics/terraform/spark-eks-ipv6/README.md
- analytics/terraform/spark-k8s-operator/README.md
- analytics/terraform/spark-k8s-operator/versions.tf
- distributed-databases/cloudnative-postgres/README.md
- distributed-databases/trino/README.md
- schedulers/terraform/argo-workflow/README.md
- schedulers/terraform/aws-batch-eks/README.md
- schedulers/terraform/managed-airflow-mwaa/README.md
- schedulers/terraform/self-managed-airflow/README.md
- streaming/emr-eks-flink/README.md
- streaming/flink/README.md
- streaming/kafka/README.md
- streaming/nifi/README.md
- streaming/spark-streaming/terraform/README.md
- website/docs/bestpractices/analytics/trino-best-practices.md
This PR updates the pre-commit configuration and the workflow that runs the pre-commit hooks as one of the checks on new PRs to address #831. 
Removing the cache and letting each blueprint pull the plugins to it's own `*/.terraform/` directory baloons the whole project directory >25GB. A terraform cache is highly recommended.
To work around this I set `--hook-config=--parallelism-limit=1` in the arguements for the `terraform_valdate` hook. This has a couple of side effects:
- the first run for this hook can take 15min+ depending on the system as it will run `terraform init` across each blueprint 1 at a time.
- without a cache, each blueprint will also need to pull the plugins to it's own directory in the repo/workspace.
I've also updated the Github cache configuration so that a cache is …
> ci: Pre commit fixes

- analytics/cdk/stream-emr-on-eks/source/lib/emr_on_ec2_stack.py
- analytics/terraform/emr-eks-karpenter/README.md
- analytics/terraform/emr-eks-karpenter/addons.tf
- analytics/terraform/spark-k8s-operator/README.md
- analytics/terraform/spark-k8s-operator/addons.tf
- Upgraded Spark History Server with new versions
- EKS Data addons upgrade to use the latest
- fixed chart_version to version
> fix: Spark History server upgrade

- streaming/flink/addons.tf
- streaming/flink/karpenter-provisioners/flink-compute-optimized-provisioner.yaml
- streaming/flink/karpenter-provisioners/flink-graviton-memory-optimized-provisioner.yaml
- streaming/flink/karpenter-provisioners/flink-memory-optimized-provisioner.yaml
- streaming/flink/main.tf
🛑 Resolve issue - Flink module uses invalid Karpenter version #849
Doing a PoC Flink on EKS
```
% kg ec2nodeclasses.karpenter.k8s.aws                               
NAME                              READY   AGE
flink-compute-optimized           True    120m
flink-graviton-memory-optimized   True    120m
flink-memory-optimized            True    120m
% kg nodepools.karpenter.sh                               
NAME                              NODECLASS                         NODES   READY   AGE
flink-compute-optimized           flink-compute-optimized           2       True    120m
flink-graviton-memory-optimized   flink-graviton-memory-optimized   0       True    120m
flink-memory-optimized            flink-memory-optimized            0       True    120m
% kubectl get deployments -n …
```
> fix: karpenter version in module flink on eks

- analytics/terraform/spark-k8s-operator/install.sh
- Ensuring that GP3 storage is deployed before the actual addons which requires this storage class to create EBS Volumes
> feat: Deploying gp3 storage class before the addons to avoud race condition

- schedulers/terraform/aws-batch-eks/README.md
- schedulers/terraform/aws-batch-eks/addons.tf
- streaming/spark-streaming/terraform/README.md
- streaming/spark-streaming/terraform/apps.tf
Pins the IRSA module version used in the XX and XX blueprints to avoid breaking changes. 
We should update the blueprints to use Pod Identity instead, or ensure the latest modules work (i think the module dropped `eks` in the path). As a stop gap this PR pins the modules to the previous versions.
Resolves #891
I did not deploy out the blueprints that have been updated, but the pre-commit checks are all passing locally.
> chore: Pin IRSA module version

- website/docs/blueprints/streaming-platforms/emr-eks-flink.md
Incorrect URL used within documentation
Updating the URL within the EMR-EKS-Flink blueprint documentation to point to the correct place.
> docs: Update EMR on EKS with Flink Streaming documentation

- .github/workflows/plan-examples.yml
- .github/workflows/pre-commit.yaml
- .github/workflows/website-deploy.yaml
- .github/workflows/website-test-deploy.yml
- analytics/terraform/spark-k8s-operator/examples/benchmark/spark-operator-benchmark-kit/requirements.txt
- distributed-databases/cloudnative-postgres/README.md
- distributed-databases/cloudnative-postgres/data.tf
- streaming/emr-eks-flink/README.md
- streaming/emr-eks-flink/main.tf
- website/package-lock.json
- Fixed security recommendations from code scanning alerts
- Fixed pre-commit errors with terraform validate
> feat: Security fix and pre-commit fixes
